apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev-v2
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes-manifests/dev-v2
    repoURL: https://github.com/supirman/nd064_capstone
    targetRevision: HEAD
  syncPolicy:
    automated: {}
