apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-prod 
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes-manifests/prod
    repoURL: https://github.com/supirman/nd064_capstone
    targetRevision: HEAD
  syncPolicy: {}
