apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: prod
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    nodePort: 30040
    port: 80
    targetPort: 8080