name: Uda'CityShop [sha tag] - Package with Docker

on:
  push:
    branches:
      - 'master'
      - 'main'
    paths:
      - 'src/**'

jobs:
  changes: 
    runs-on: ubuntu-latest
    outputs: 
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            adservice:
              - 'src/adservice/**'
            adservice-v2:
              - 'src/adservice-v2/**'
            currencyservice:
              - 'src/currencyservice/**'
            frontend:
              - 'src/frontend/**'
            productcatalogservice:
              - 'src/productcatalogservice/**'
  
  build-and-push:
    name: Build and Push
    needs: changes
    if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
    strategy:
      matrix:
        service: ${{ fromJson(needs.changes.outputs.services) }}
        # service: [adservice, adservice-v2, currencyservice, frontend, productcatalogservice]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/udacityshop-${{ matrix.service }}
          tags: |
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/${{ matrix.service }}/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
